image: Visual Studio 2019  # образ для сборки
version: '1.0.{build}'
stack: node v18.14.1  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test # скрипт тестирования
